import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RegisterServerComponents from "./register";
import "@/assets/icons/ali/iconfont.css";
import "./globals.scss";
import "normalize.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterServerComponents>{children}</RegisterServerComponents>
      </body>
    </html>
  );
}
